import { Router } from 'express';
import { authRoutes } from '../modules/auth/auth.routes.js';
import { usersRoutes } from '../modules/users/users.routes.js';
import { rolesRoutes } from '../modules/roles/roles.routes.js';
import { warehousesRoutes } from '../modules/warehouses/warehouses.routes.js';
import { locationsRoutes } from '../modules/locations/locations.routes.js';
import { unitsRoutes } from '../modules/units/units.routes.js';
import { categoriesRoutes } from '../modules/categories/categories.routes.js';
import { brandsRoutes } from '../modules/brands/brands.routes.js';
import { suppliersRoutes } from '../modules/suppliers/suppliers.routes.js';
import { customersRoutes } from '../modules/customers/customers.routes.js';
import { productsRoutes } from '../modules/products/products.routes.js';
import { inventoryRoutes } from '../modules/inventory/inventory.routes.js';
import { movementsRoutes } from '../modules/movements/movements.routes.js';
import { receivingRoutes } from '../modules/receiving/receiving.routes.js';
import { putAwayRoutes } from '../modules/putaway/putaway.routes.js';
import { transfersRoutes } from '../modules/transfers/transfers.routes.js';
import { pickingRoutes } from '../modules/picking/picking.routes.js';
import { packingRoutes } from '../modules/packing/packing.routes.js';
import { controllingRoutes } from '../modules/controlling/controlling.routes.js';
import { dashboardRoutes } from '../modules/dashboard/dashboard.routes.js';
import { reportsRoutes } from '../modules/reports/reports.routes.js';
import { notificationsRoutes } from '../modules/notifications/notifications.routes.js';
import { auditRoutes } from '../modules/audit/audit.routes.js';

export const api = Router();

api.use('/auth', authRoutes);
api.use('/users', usersRoutes);
api.use('/roles', rolesRoutes);
api.use('/warehouses', warehousesRoutes);
api.use('/locations', locationsRoutes);
api.use('/units', unitsRoutes);
api.use('/categories', categoriesRoutes);
api.use('/brands', brandsRoutes);
api.use('/suppliers', suppliersRoutes);
api.use('/customers', customersRoutes);
api.use('/products', productsRoutes);
api.use('/inventory', inventoryRoutes);
api.use('/movements', movementsRoutes);
api.use('/receiving', receivingRoutes);
api.use('/putaway', putAwayRoutes);
api.use('/transfers', transfersRoutes);
api.use('/picking', pickingRoutes);
api.use('/packing', packingRoutes);
api.use('/controlling', controllingRoutes);
api.use('/dashboard', dashboardRoutes);
api.use('/reports', reportsRoutes);
api.use('/notifications', notificationsRoutes);
api.use('/audit-logs', auditRoutes);
